run:
  timeout: 5m
  skip-dirs:
    - vendor
    - third_party
    - node_modules
    - ".*testdata"
  skip-files:
    - ".*_test.go"
  skip-dirs-use-default: true
  modules-download-mode: readonly
  go: "1.21"
  
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
  
linters-settings:
  goimports:
    local-prefixes: github.com/AccursedGalaxy/noidea
  
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    - path: internal/secure/keyring.go
      text: "mnd" # Exclude the "magic number detector" warnings
    - path: "^golang.org/toolchain"
      linters:
        - all
    - path: "^github.com/go/pkg/mod"
      linters:
        - all
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: true
