version: "2"

run:
  timeout: 5m
  skip-dirs:
    - vendor
  skip-files:
    - "\.pb\.go$"
  skip-dirs-use-default: true
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true
  go: "1.23"
  build-tags:
    - netgo
    - osusergo

linters:
  disable-all: true
  enable:
    - errcheck      # Checks for unchecked errors
    - gosimple      # Simplifies code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Go static analysis
    - unused        # Checks for unused constants, variables, etc.
    - gofmt         # Checks if code is formatted
    - goimports     # Manages imports
    - misspell      # Finds misspelled words
  fast: false

linters-settings:
  goimports:
    local-prefixes: github.com/AccursedGalaxy/noidea

issues:
  exclude-dirs:
    - vendor/
    - .git/
  exclude-files:
    - ".*\\.go\\.mod$"
    - ".*\\.pb\\.go$"
    - "^\\.\\./"
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: cmd/.*\.go
      text: "unused"
      linters:
        - unused
    - source: "// nolint"
      linters:
        - all
    - path: "internal/secure/keyring.go"
      text: "undefined: keyring"
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: true 