authors:
  accursedgalaxy:
    name: Accursed Galaxy
    description: Creator of NoIdea - Git assistant with AI powers & sassy feedback
    avatar: https://github.com/AccursedGalaxy.png
    url: https://github.com/AccursedGalaxy 