title: noidea
description: Git assistant with AI commit messages and sassy feedback
baseurl: "/noidea" # the subpath of your site, e.g. /blog
url: "https://accursedgalaxy.github.io" # use your GitHub username instead

# Build settings
markdown: kramdown
highlighter: rouge

# Theme settings - comment out to use our custom theme
# remote_theme: just-the-docs/just-the-docs
# color_scheme: dark

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Aux links for the upper right navigation
aux_links:
  "noidea on GitHub":
    - "//github.com/AccursedGalaxy/noidea"

# Footer content
footer_content: "Copyright &copy; 2023 AccursedGalaxy. Distributed under an MIT license."

# Default layout for pages
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

# Collections for site structure
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    docs:
      name: Documentation 