title: noidea - Git Assistant
description: A Git companion with AI commit messages and sassy feedback
baseurl: "/noidea" # the subpath of your site, e.g. /blog
url: "https://accursedgalaxy.github.io" # the base hostname & protocol for your site
github_username: AccursedGalaxy

# Build settings
markdown: kramdown
# Using remote_theme instead of theme for non-standard themes
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache

# Theme settings
logo: /assets/images/header.png
show_downloads: true

# Just the Docs specific settings
aux_links:
  "noidea on GitHub":
    - "https://github.com/AccursedGalaxy/noidea"
search_enabled: true 