title: noidea - Git Assistant
description: A Git companion with AI commit messages and sassy feedback
baseurl: "/noidea" # the subpath of your site, e.g. /blog
url: "https://accursedgalaxy.github.io" # the base hostname & protocol for your site
github_username: AccursedGalaxy

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache

# Theme settings
show_downloads: true

# Navigation
nav:
  - name: Home
    url: /
  - name: Installation
    url: /installation
  - name: Usage
    url: /usage
  - name: Commands
    url: /commands
  - name: Configuration
    url: /configuration
  - name: Personalities
    url: /personalities
  - name: FAQ
    url: /faq

# Enable copy code button
enable_copy_code_button: true

# Footer content
footer_content: "Copyright &copy; 2025 Accursed Galaxy. Distributed under an <a href=\"https://github.com/AccursedGalaxy/noidea/blob/main/LICENSE\">MIT license.</a>" 