title: noidea
description: Git assistant with AI commit messages and sassy feedback
baseurl: "/noidea"
url: "https://accursedgalaxy.github.io"

# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs
theme: jekyll-theme-cayman # Fallback theme

# Enable search
search_enabled: true

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Aux links for the upper right navigation
aux_links:
  "noidea on GitHub":
    - "//github.com/AccursedGalaxy/noidea"

# Footer content
footer_content: "Copyright &copy; 2023 AccursedGalaxy. Distributed under an MIT license."

# Default layout for pages
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

# Collections for site structure
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    docs:
      name: Documentation 